---
- hosts: servers
  become: true
  tasks:
    - name: Actualizar la caché de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar Cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear un archivo
      file:
        path: /home/vagrant/testfile.txt
        state: touch

    - name: Copiar archivos
      copy:
        src: /ruta/origen/archivo.txt
        dest: /ruta/destino/

    - name: Crear carpetas
      file:
        path: /home/vagrant/nueva_carpeta
        state: directory

    - name: Iniciar servicio Apache
      service:
        name: apache2
        state: started

    - name: Agregar un usuario
      user:
        name: nuevo_usuario
        state: present
        password: "{{ 'password' | password_hash('sha512') }}"

    - name: Ejecutar un script en el servidor
      command: /ruta/a/tu/script.sh